
static const unsigned char cg_vertex_str[] =
{
  "\n"
  "struct vpin\n"
  "{\n"
  "\tfloat4 pos : POSITION;\n"
  "\tfloat4 col0 : COLOR0;\n"
  "\tfloat4 col1 : ATTR6;\n"
  "\tfloat4 tex[8] : TEXCOORD0;\n"
  "\tfloat fog : FOGCOORD;\n"
  "};\n"
	"\n"
  "struct vpout\n"
  "{\n"
  "\tfloat4 pos : POSITION;\n"
  "\tfloat4 col[2] : COLOR0;\n"
  "\tfloat4 tex[8] : TEXCOORD0;\n"
  "\tfloat fog : FOG;\n"
  "\tfloat4 wpos : WPOS;\n"
  "};\n"
	"\n"
  "float4x4 smprojection : STATE.MATRIX.PROJECTION;\n"
	"\n"
  "vpout main (vpin IN)\n"
  "{\n"
  "\tvpout OUT;\n"
	"\n"
  "\tOUT.pos = mul (smprojection, IN.pos);\n"
  "\tOUT.col[0] = IN.col0;\n"
  "\tOUT.col[1] = IN.col1;\n"
  "\tOUT.tex[0] = IN.tex[0];\n"
  "\tOUT.tex[1] = IN.tex[1];\n"
  "\tOUT.tex[2] = IN.tex[2];\n"
  "\tOUT.tex[3] = IN.tex[3];\n"
  "\tOUT.tex[4] = IN.tex[4];\n"
  "\tOUT.tex[5] = IN.tex[5];\n"
  "\tOUT.tex[6] = IN.tex[6];\n"
  "\tOUT.tex[7] = IN.tex[7];\n"
  "\tOUT.fog = 1 - IN.pos.z;\n"
	"\n"
  "\treturn OUT;\n"
  "}\n"
};
